name: Deploy to VPS

on:
  push:
    branches: ["master"]   # sempre que fizer push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Copiar código para VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/www/wwwroot/bet"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /www/wwwroot/bet
            docker-compose down
            docker-compose up -d --build
